_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.4
            "6": 4.45.2
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-arm64
architecture:
    value: GeoCLIP
dataset:
    value: Finetuning on GeoGuessing/GeoTaggedImages
epochs:
    value: 10
learning_rate:
    value: 3e-05
